import AuthProvider from "./components/AuthProvider"
import TanstackProvider from "./components/TanstackProvider"

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <TanstackProvider>
            {children}
          </TanstackProvider>
        </AuthProvider>
      </body>
    </html>
  )
}
